// <auto-generated />
using System;
using ContactTrackingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactTrackingSystem.Migrations
{
    [DbContext(typeof(CTSDbContext))]
    [Migration("20250202173335_SeedDataUsers")]
    partial class SeedDataUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactTrackingSystem.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            ContactId = new Guid("9cfdf9cc-d423-4efe-b46c-06e40361af0c"),
                            EmailAddress = "jgenge0@moonfruit.com",
                            FirstName = "Jarvis",
                            LastName = "Genge",
                            PhoneNumber = "160-614-7833",
                            ZipCode = "88358"
                        },
                        new
                        {
                            ContactId = new Guid("56079b0c-6328-4f81-a91b-e664d5ad1c25"),
                            EmailAddress = "dratchford1@indiatimes.com",
                            FirstName = "Duff",
                            LastName = "Ratchford",
                            PhoneNumber = "138-493-8133",
                            ZipCode = "83740"
                        },
                        new
                        {
                            ContactId = new Guid("90f55200-ee3c-45e6-ab14-ca8e1951c29a"),
                            EmailAddress = "bgiff2@toplist.cz",
                            FirstName = "Bancroft",
                            LastName = "Giff",
                            PhoneNumber = "370-491-2907",
                            ZipCode = "73970"
                        },
                        new
                        {
                            ContactId = new Guid("83c4c256-ffbd-4bbc-b527-d49389ccfbae"),
                            EmailAddress = "cgribbins3@wikipedia.org",
                            FirstName = "Clea",
                            LastName = "Gribbins",
                            PhoneNumber = "821-170-9142",
                            ZipCode = "66497"
                        },
                        new
                        {
                            ContactId = new Guid("313e0be6-9ca5-4901-a19a-3a3c593b4b29"),
                            EmailAddress = "hmccluin4@barnesandnoble.com",
                            FirstName = "Helene",
                            LastName = "McCluin",
                            PhoneNumber = "170-986-3084",
                            ZipCode = "32879"
                        },
                        new
                        {
                            ContactId = new Guid("4e867020-1305-4cb1-85c3-041c04ab6758"),
                            EmailAddress = "vlimeburn5@unblog.fr",
                            FirstName = "Vassili",
                            LastName = "Limeburn",
                            PhoneNumber = "140-153-9927",
                            ZipCode = "75005"
                        },
                        new
                        {
                            ContactId = new Guid("5c5e2eb4-0319-4781-9b82-634313ec228c"),
                            EmailAddress = "emundle6@sun.com",
                            FirstName = "Enriqueta",
                            LastName = "Mundle",
                            PhoneNumber = "927-644-3552",
                            ZipCode = "78132"
                        },
                        new
                        {
                            ContactId = new Guid("1f58098d-7de6-40f4-9d13-d7cb33b02b47"),
                            EmailAddress = "akenaway7@webnode.com",
                            FirstName = "Ashia",
                            LastName = "Kenaway",
                            PhoneNumber = "735-679-5530",
                            ZipCode = "85853"
                        },
                        new
                        {
                            ContactId = new Guid("7878280e-7046-4c1a-bdc6-34ae8256d9c5"),
                            EmailAddress = "rbarrable8@newyorker.com",
                            FirstName = "Regan",
                            LastName = "Barrable",
                            PhoneNumber = "679-473-2885",
                            ZipCode = "19188"
                        },
                        new
                        {
                            ContactId = new Guid("9fe9b5d6-9a87-4edb-b083-6d54dbd802a8"),
                            EmailAddress = "alongmore9@nps.gov",
                            FirstName = "Amabelle",
                            LastName = "Longmore",
                            PhoneNumber = "307-257-3220",
                            ZipCode = "12936"
                        });
                });

            modelBuilder.Entity("ContactTrackingSystem.Models.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e977e05c-17c1-4144-91a9-50a4143d4ee9"),
                            Password = "Test!234",
                            Username = "AdminUser@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
